---
mysql_community_noarch_rpm:
  - https://dev.mysql.com/get/mysql57-community-release-el{{ ansible_distribution_major_version }}-11.noarch.rpm

mysql_install_package_list:
  - mysql-community-server

mysql_root_password: passwordPASSWORD@999
